// <auto-generated />
namespace Borrowee.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class BackOutImageMapping : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BackOutImageMapping));
        
        string IMigrationMetadata.Id
        {
            get { return "202012250218527_BackOutImageMapping"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
